# Generated by Django 4.2.7 on 2023-11-19 20:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='SavedQueries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_name', models.CharField(max_length=250)),
                ('query_description', models.TextField()),
                ('first_country', models.CharField(default='Colombia', max_length=100)),
                ('second_country', models.CharField(blank=True, max_length=100, null=True)),
                ('first_date', models.DateField(default=datetime.datetime(2023, 11, 19, 20, 42, 26, 66395, tzinfo=datetime.timezone.utc))),
                ('second_date', models.DateField(blank=True, null=True)),
                ('query_quantity', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comparision_tool.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comparision_tool.customuser')),
                ('saved_query_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comparision_tool.savedqueries')),
            ],
        ),
    ]
