# Generated by Django 4.2.7 on 2023-11-20 05:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparision_tool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedqueries',
            name='first_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 20, 5, 1, 26, 21092, tzinfo=datetime.timezone.utc)),
        ),
    ]
